config/routes.rb
Dmp40k::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match '/rules' => 'pages#rules', :as => 'rules'

  match '/painting_contest' => 'pages#contest', :as => 'contest'

  match '/directions' => 'pages#directions', :as => 'directions'

  match '/admin' => 'admin#index'

  resources :players do
    resources :tournament_registrations
  end

  resources :sessions

  resources :users

  resources :teams

  resources :hostel_bookings do
    member do
      get 'toggle_payment'
    end
  end


  resources :tournaments do
    namespace :play do
      resources :players
      resources :results
      resources :tournaments
      resources :tournament_pairings, :as => 'pairings', :only => [:index, :update, :show]
    end
    resource :play
    resources :posts
    resources :pages do
      member { post :mercury_update }
    end

    resources :team_registrations do
      member do
        get 'toggle'
      end
    end

    resources :tournament_registrations, :path => "registrations" do
      collection do
        get 'players'
      end
      member do
        get 'toggle_payment', :as => 'toggle_payment'
        get 'toggle_rosters'
        get 'toggle_rosters_validation'
      end
    end
    member do
      get 'generate_pairings'
      get 'results'
      get 'current_round'
      get 'generate_rank_csv'
    end
  end




  namespace :admin do
    resources :players do
      collection do
        post 'import'
      end
    end

    resources :tournaments do
      member { post 'add_to_rank' }
    end

    root :to => 'tournaments#index'
  end


  namespace :rank do

    resources :rank_places, path: 'player_results', as: 'player_results'

    match 'upload_results', to: 'rank_places#upload_results'
    match 'preview_tournament', to: 'rank_places#preview_tournament'

    root :to => 'rank_places#index'
  end

  root :to => 'tournaments#index'
end

app/models/tournament.rb
#encoding: utf-8

class Tournament < ActiveRecord::Base
  extend FriendlyId
  include AASM
  include TournamentsHelper

  mount_uploader :results, ResultsUploader

  TournamentRanks = ['Lokal', 'Czelendżer', 'Master']
  RankPoints = {
                'Lokal' => 3, 'Czelendżer' => 5, 'Master' => 5
               }.freeze

  BASE_RANK_POINTS = {
    'Lokal' => 20, 'Czelendżer' => 35, 'Master' => 50
  }.freeze


  attr_accessor :results_required
  validates_presence_of :name, :rank, :start_date, :city, :number_of_rounds #add date
  validates_numericality_of :number_of_rounds, :greater_than => 0
  validates_uniqueness_of :name
  validates_presence_of :team_members_count, :if => Proc.new { |t| t.for_teams? }
  validates_presence_of :results, :if => Proc.new { |t| t.results_required.present? }

  belongs_to :user
  has_many :pairings, :class_name => "TournamentPairing", :dependent => :destroy
  has_many :pages, :dependent => :destroy
  has_many :tournament_registrations, :dependent => :destroy
  has_many :team_registrations, :dependent => :destroy
  has_many :team_pairings, :class_name => "TournamentTeamPairing", :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :played_tournaments, :dependent => :destroy
  friendly_id :name, use: :slugged
  #has_many :hostel_bookings, :dependent => :destroy

  after_create :import_results

  aasm :column => 'state' do

    state :new, :initial => true
    state :ongoing
    state :finished
    state :counted
    state :imported

    event :start do
      transitions from: :new, to: :ongoing
    end

    event :finish do
      transitions from: :ongoing, to: :finished
    end

    event :count do
      transitions from: [:finished, :imported], to: :counted
    end

    event :uncount do
      transitions from: :counted, to: :finished
    end
  end

  def import_results
    return true unless results.present?

    CSV.parse(results.read, headers: true, col_sep: ';') do |row|
      puts row
      break if row[0].match(/Runda/)
      create_registration(row)

    end

    self.update_column(:state, 'imported')
  end

  def create_registration(row)
    reg = self.tournament_registrations.create(
          player_id: Player.find_or_create_by_league_id(row[1]).id,
          army: row[4],
          current_points: row[6],
          current_victory_points: row[6],
          played_games: self.number_of_rounds,
          extra_points: 0,
          penalty_points: 0)

    # self.played_tournaments.create(
    #       player_id: reg.player_id,
    #       place: row[0],
    #       points: row[6],
    #       registration_id: reg.id)

  end

  def update_round
    increment!(:current_round)
  end

  TournamentRanks.each do |meth|
    define_method("is_#{meth.downcase}?".to_sym) do
      self.rank == meth
    end
  end

  def round_completed?
    if for_teams?
      team_pairings.where(:round => current_round).select{|p| p.invalid?(:update)}.empty?
    else
      pairings.where(:round => current_round).select{|p| p.invalid?(:update)}.empty?
    end
  end

  def get_pairings
    if for_teams?
      team_pairings
    else
      pairings
    end
  end

  def generate_pairings
    return false if last_round?
    transaction do
      check_round
      registrations = prepare_registrations
      create_pairings(registrations)
      return true
    end
  end

  def prepare_registrations
    registrations = for_teams? ? team_registrations : tournament_registrations
    if current_round == 1
      registrations = registrations.shuffle
    else
      registrations = sort_players(registrations)
    end
    registrations = remove_pausing_pairing(registrations) if registrations.size.odd?
    registrations

  end

  def check_round
    if current_round == 0
      start!
      update_round
    else
      update_round
    end
  end

  def create_pairings(registrations)
    table = 1
    sorted_registrations = prepare_list(registrations)
    sorted_registrations.each_slice(2) do |p1, p2|
      if for_teams?
        team_pairings.create(:team1_id => p1.id, :team2_id => p2.id, :round => current_round, :table => table)
      else
        pairings.create(:player1_id => p1.player_id, :player2_id => p2.player_id, :round => current_round, :table => table)
      end
      table += 1
    end
  end

  def prepare_list(registrations)
    sorted_players = []
    while registrations.any? do
      p1 = registrations.shift
      sorted_players << p1
      index = 0
      while player_or_team(p1).played_with?(registrations[index]) do
        index += 1
      end
      sorted_players << registrations.slice!(index)
    end
    sorted_players.compact
  end

  def player_or_team(registration)
    if registration.class.name == 'TournamentRegistration'
      registration.player
    else
      registration
    end
  end


  def sort_players(registrations)
    registrations.sort_by { |registration| [registration.current_points, registration.current_victory_points] }.reverse
  end

  def last_round?
    current_round == number_of_rounds
  end

  def can_finish?
    last_round? && round_completed? && !finished?
  end

  def pausing_pairing
    pairings.where(:pausing => true)
  end

  def rank_points
    Tournament::BASE_RANK_POINTS[rank]
  end

  def self.past
    where('start_date < ?', Time.now)
  end

  def self.upcomming
    where('start_date > ?', Time.now)
  end

  def points_for_registration(reg)
    if for_teams?
      registrations = team_registrations.sort{|a,b| b.final_points <=> a.final_points}
    else
      registrations = tournament_registrations.sort{|a,b| b.final_points <=> a.final_points}
    end
    base = (registrations.size < 15 && is_lokal?) ? 5 + registrations.size : rank_points
    place = registrations.index(reg) + 1
    rank = Tournament::RankPoints[self.rank]
    extra_points = place <= rank ? rank + 1 - place : 0

    points = (base.to_f * (registrations.size + 1 - place) / registrations.size).ceil + extra_points
  end

  def add_to_rank
    regs = sort_players(tournament_registrations)
    transaction do
      regs.each_with_index do |reg, i|
        PlayedTournament.create(player_id: reg.player_id,
                                tournament_id: self.id,
                                place: i+1,
                                points: points_for_registration(reg),
                                registration_id: reg.id)
      end
      RankPlace.update_places
      self.count!
    end
  end

  def imported_results
    Tournament.import(results.read)
  end

  def self.import(file)
    rows = []
    CSV.parse(file, headers: true, col_sep: ';') do |row|
      puts row
      break if row[0].match(/Runda/)
      rows << [row[0], row[1], row[2], row[3], row[4], row[5], row[6]]
    end
    rows
  end

  private

  def remove_pausing_pairing(players)
    pausing_player = players.pop
    create_pausing_pairing(pausing_player)
    players
  end

  def create_pausing_pairing(player)
    if player.class.name == 'TournamentRegistration'
      pairings.create(:player1_id => player.player.id, :pausing => true, :round => current_round,
                      :player1_game_points => pause_victory_points, :player2_game_points => 0,
                      :player1_match_points => pause_game_points, :player2_match_points => 0)
    else
      team_pairings.create(:team1_id => player.id, :pausing => true, :round => current_round, :team1_game_points => 5, :team2_game_points => 0, :team1_match_points => 15, :team2_match_points => 0)
    end
  end
end

app/controllers/admin/tournaments_controller.rb
#encoding: utf-8

class Admin::TournamentsController < AdminController

  def index
    @tournaments = Tournament.all(:order => 'start_date DESC')
  end

  def add_to_rank
    tournament = Tournament.find(params[:id])
 
    if tournament.add_to_rank 
      redirect_to admin_tournaments_path, :notice => "Turniej dodany do rankingu"
    else
      redirect_to admin_tournaments_path, :notice => "Nie udało się dodać do rankungu"
    end
  end
end

app/controllers/tournaments_controller.rb
#encoding: utf-8
class TournamentsController < ApplicationController
  before_filter :load_tournament

  respond_to :json

  def show
    respond_to do |format|
      format.html{ redirect_to tournament_posts_path(@tournament) }
    format.json{ render json: @tournament }
    end
  end

  def index
    @tournaments = Tournament.all(:order => 'start_date DESC')
  end

  def new
    @tournament = Tournament.new 
  end

  def create
    @tournament = Tournament.new(params[:tournament])
    @tournament.user = current_user
    if @tournament.save
      redirect_to tournament_posts_path(@tournament), :notice => "Tournament created"
    else
      render :action => 'new'
    end
  end

  def generate_pairings
    if @tournament.round_completed?
      if @tournament.generate_pairings
        @pairings = @tournament.get_pairings
        render json: @pairings, root: false
      else
        render :json => {:msg => 'Aktualne runda jest ostatnią', :code => '400'}, :status => 422
      end
    else
      render :json => {:msg => 'Wprowadź wszystkie wyniki', :code => '400'}, :status => 422
    end
  end


  def results
    if @tournament.for_teams?
      @results = @tournament.team_registrations.includes(:players).sort_by{|r| [r.final_points, r.current_points, r.current_victory_points ]}.reverse
    else
      @results = @tournament.tournament_registrations.includes(:player).sort_by{|r| [r.final_points, r.current_points, r.current_victory_points ]}.reverse
    end
    respond_to do |format|
      format.html
      format.csv do
        if @tournament.for_teams?
          send_data TeamRegistration.to_csv(@results) 
        else
          send_data TournamentRegistration.to_csv(@results) 
        end
      end
    end
  end

  def current_round
    if @tournament.for_teams?
      @pairings = @tournament.team_pairings.where(:round => @tournament.current_round).order('tournament_team_pairings.table ASC')
    else
      @pairings = @tournament.pairings.where(:round => @tournament.current_round).order('tournament_pairings.table ASC')
    end
    render :layout => 'play'
  end

end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  
  def rank_points(tournament, result)
    if tournament.for_teams?
      registrations = tournament.team_registrations.sort{|a,b| b.final_points <=> a.final_points}
    else
      registrations = tournament.tournament_registrations.sort{|a,b| b.final_points <=> a.final_points}
    end
    base = (registrations.size < 15 && tournament.is_lokal?) ? 5 + registrations.size : tournament.rank_points
    place = registrations.index(result) + 1
    rank = Tournament::RankPoints[tournament.rank]
    extra_points = place <= rank ? rank + 1 - place : 0
  
    points = (base.to_f * (registrations.size + 1 - place) / registrations.size).ceil + extra_points
  end

end

app/views/tournaments/_result.html.haml
%tr
  %td
    =result_counter + 1
  -if result.class.name == 'TournamentRegistration'
    %td
      =result.player.full_name
    %td
      =result.army
  -else
    %td
      =result.name
    %td
      =result.armies
  %td
    =result.current_victory_points
  %td
    =result.current_points
  %td
    =result.final_points
  %td
    =result.extra_points
  %td
    =result.penalty_points
  %td
    =rank_points(@tournament, result)

app/views/tournaments/_tournament.html.haml
%tr
  %th
    = "#{i + 1}"
  %th
    =link_to t.name, tournament_posts_path(t)
  %th
    =t.city
  %th
    =t.rank
  %th
    =t.start_date.to_date rescue ''

app/views/tournaments/current_round.html.erb
<header>
  <h1>Pary na rundę: <%= @tournament.current_round %></h1>
  <p>Naciśnij F11 aby przejść w tryb pełnoekranowy<p>
<header>
<table class='table table-bordered current_round'>
  <thead>
    <th>
      Stół
    </th>
    <th>
      Gracz 1
    </th>
    <th>
      Gracz 2
    </th>
  </thead>
  <tbody>
    <% @pairings.each do |p| %>
      <tr>
        <td><%= p.table %></td>
        <% if @tournament.for_teams? %>
          <td><%= p.team1.name rescue 'pauza' %></td>
          <td><%= p.team2.name rescue 'pauza'%></td>
        <% else %>
          <td><%= p.player1.full_name rescue 'pauza' %></td>
          <td><%= p.player2.full_name rescue 'pauza'%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tournaments/index.html.haml
%table.table.table-bordered.tablesorter
  %thead
    %tr
      %th
        Lp.
      %th
        Nazwa turnieju
      %th
        Ranga
      %th
        Miasto
      %th
        Data
  %tbody
    -@tournaments.each_with_index do |t, i|
      =render :partial => 'tournament', :locals => {:t => t, :i => i}
-if logged_in?
  %div
    %h3=link_to 'Utwórz nowy turniej', new_tournament_path
 

app/views/tournaments/new.html.haml
=form_for @tournament do |f|
  -@tournament.errors.full_messages.each do |msg|
    %li= msg 
  %p
    =f.label 'Nazwa'
    =f.text_field :name
    
    =f.label 'Typ'
    =f.select :rank, options_for_select(Tournament::TournamentRanks)
  %p
    =f.label 'Turniej drużynowy(także parowy)'
    =f.check_box :for_teams
    
    =f.label 'Ilość graczy w drużynie'
    =f.text_field :team_members_count
  %p
    =f.label 'Ilość rund'
    =f.text_field :number_of_rounds

    =f.label 'Duże punkty za pauzę'
    =f.text_field :pause_game_points

    =f.label 'Małes punkty za pauzę'
    =f.text_field :pause_victory_points
    
    =f.label 'Data rozpoczęcia'
    =f.text_field :start_date, class: "datepicker"
  %p
    =f.label 'Miasto'
    =f.text_field :city
  %p
    =f.submit 'Utwórz turniej', :class => 'btn'

app/views/tournaments/results.html.haml
%h2= "#{@tournament.name} - wyniki"
-if owner_or_admin?
  %p.generate_csv
    %button
      =link_to 'Wygeneruj plik csv do rankingu', results_tournament_path(@tournament, :format => 'csv')
%table.table.table-bordered.tablesorter
  %thead
    %tr
      %th
        Miejsce
      -if @tournament.for_teams?
        %th
          Drużyna  
        %th
          Armie
      -else
        %th
          Gracz  
        %th
          Armia
      %th
        VP
      %th
        Suma bitwy
      %th
        Suma pkt.
      %th
        Pkt. dodatkowe
      %th
        Pkt. karne
      %th
        Pkt. rankingowe
  %tbody
    =render :partial => 'result', :collection => @results