config/routes.rb
Dmp40k::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match '/rules' => 'pages#rules', :as => 'rules'

  match '/painting_contest' => 'pages#contest', :as => 'contest'

  match '/directions' => 'pages#directions', :as => 'directions'

  match '/admin' => 'admin#index'

  resources :players do
    resources :tournament_registrations
  end

  resources :sessions

  resources :users

  resources :teams

  resources :hostel_bookings do
    member do
      get 'toggle_payment'
    end
  end


  resources :tournaments do
    namespace :play do
      resources :players
      resources :results
      resources :tournaments
      resources :tournament_pairings, :as => 'pairings', :only => [:index, :update, :show]
    end
    resource :play
    resources :posts
    resources :pages do
      member { post :mercury_update }
    end

    resources :team_registrations do
      member do
        get 'toggle'
      end
    end

    resources :tournament_registrations, :path => "registrations" do
      collection do
        get 'players'
      end
      member do
        get 'toggle_payment', :as => 'toggle_payment'
        get 'toggle_rosters'
        get 'toggle_rosters_validation'
      end
    end
    member do
      get 'generate_pairings'
      get 'results'
      get 'current_round'
      get 'generate_rank_csv'
    end
  end




  namespace :admin do
    resources :players do
      collection do
        post 'import'
      end
    end

    resources :tournaments do
      member { post 'add_to_rank' }
    end

    root :to => 'tournaments#index'
  end


  namespace :rank do

    resources :rank_places, path: 'player_results', as: 'player_results'

    match 'upload_results', to: 'rank_places#upload_results'
    match 'preview_tournament', to: 'rank_places#preview_tournament'

    root :to => 'rank_places#index'
  end

  root :to => 'tournaments#index'
end

app/models/hostel_booking.rb
class HostelBooking < ActiveRecord::Base

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email

end

app/controllers/hostel_bookings_controller.rb
class HostelBookingsController < ApplicationController

  def index
    @bookings = HostelBooking.order('created_at ASC')
    @booking = HostelBooking.new
  end
  
  def create
    booking = HostelBooking.new(params[:hostel_booking])
    if booking.save
      redirect_to hostel_bookings_path, :notice => "Booking added"
    else
      redirect_to hostel_bookings_path, :notice => "Failed to add booking"
    end
  end

  def edit
    @booking = HostelBooking.find(params[:id]) 
  end
  
  def update
    @booking = HostelBooking.find(params[:id])

    if @booking.update_attributes(params[:hostel_booking])
      redirect_to hostel_bookings_path, :notice => "Booking updated"
    else
      render :edit, :notice => "Failed to update booking"
    end
  end

  def destroy
    booking = HostelBooking.find(params[:id])
    if booking.delete
      redirect_to hostel_bookings_path, :notice => "Booking removed"
    else
      redirect_to hostel_bookings_path, :notice => "Failed to remove booking"
    end
  end
      
  def toggle_payment
    booking = HostelBooking.find(params[:id])
    booking.update_attributes(:payment => booking.payment? ? false : true)
    redirect_to hostel_bookings_path
  end 

end

app/helpers/hostel_bookings_helper.rb
module HostelBookingsHelper
end

app/views/hostel_bookings/_booking.html.haml
%tr
  %th
    = "#{i + 1}"
  %th
    =booking.first_name
  %th
    =booking.last_name
  %th
    =booking.email
  %th
    =booking.payment? ? "tak" : "nie"
    -if logged_in?
      =link_to "", toggle_payment_hostel_booking_path(booking), :style => "margin-left:8px", :class => "#{booking.payment? ? 'icon-remove' : 'icon-ok'}"
  -if logged_in?
    %th
      =link_to "", edit_hostel_booking_path(booking), :class => 'icon-edit'
      =link_to "", hostel_booking_path(booking), :class => 'icon-remove', :method => :delete, :confirm => "Are you sure?"

app/views/hostel_bookings/_form.html.haml
.add_team
  %p
    ="#{@booking.new_record? ? 'Dodaj rezerwację' : 'Edytuj rezerwację'}"
  = form_for @booking do |f|
    %p
      = f.label :first_name, "Imie"
      = f.text_field :first_name
    %p
      = f.label :last_name, "Nazwisko"
      = f.text_field :last_name
    %p
      = f.label :email, "Email"
      = f.email_field :email
    %p  
      = f.submit (@booking.new_record? ? "Dodaj rezerwację" : "Uaktualnij")

app/views/hostel_bookings/edit.html.haml
.add_team
  = form_for @booking do |f|
    %p
      = f.label :first_name, "Imię"
      = f.text_field :first_name
    %p
      = f.label :last_name, "Nazwiskp"
      = f.text_field :last_name
    %p
      = f.label :email, "Email"
      = f.email_field :email
    %p
      = f.label :payment, "Przedpłata"
      = f.check_box :payment
    = f.submit (@booking.new_record? ? "Dodaj" : "Uaktualnij")

app/views/hostel_bookings/index.html.haml
%h3
  Noclegi
.body
  %h4
    Hostel
  %p
    Koszt: 40zł od osoby
    %br
    ul. Improwizacji 7
    %br
    01-992 Warszawa
    %br
    www.warszawanoclegi.com
  %p
    Jesli ktos/team chce miejsce to prosze o przelew do 31.03.2012 
    %br
    %span.label.label-important
      w temacie z dopiskiem - Nocleg i nazwiska osob na ktore jest rezerwacja
    %br
    Dane do przelewu:
    %br
    PL04 1140 2004 0000 3302 1466 6091
    %br
    Miłosz Dziembowski
    %br
    Ul Benisławskiego 25c/8

%p
  Lista rezerwacji

%table.table.table-bordered
  %thead
    %tr
      %th
        Lp.
      %th
        Imie
      %th
        Nazwisko
      %th
        Email
      %th
        Przedpłata
      -if logged_in?
        %th 
          Akcja
  %tbody
    -@bookings.each_with_index do |booking, i|
      =render :partial => 'booking', :locals => {:booking => booking, :i => i}

-if logged_in?
  =render :partial => 'hostel_bookings/form'