config/routes.rb
Dmp40k::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match '/rules' => 'pages#rules', :as => 'rules'

  match '/painting_contest' => 'pages#contest', :as => 'contest'

  match '/directions' => 'pages#directions', :as => 'directions'

  match '/admin' => 'admin#index'

  resources :players do
    resources :tournament_registrations
  end

  resources :sessions

  resources :users

  resources :teams

  resources :hostel_bookings do
    member do
      get 'toggle_payment'
    end
  end


  resources :tournaments do
    namespace :play do
      resources :players
      resources :results
      resources :tournaments
      resources :tournament_pairings, :as => 'pairings', :only => [:index, :update, :show]
    end
    resource :play
    resources :posts
    resources :pages do
      member { post :mercury_update }
    end

    resources :team_registrations do
      member do
        get 'toggle'
      end
    end

    resources :tournament_registrations, :path => "registrations" do
      collection do
        get 'players'
      end
      member do
        get 'toggle_payment', :as => 'toggle_payment'
        get 'toggle_rosters'
        get 'toggle_rosters_validation'
      end
    end
    member do
      get 'generate_pairings'
      get 'results'
      get 'current_round'
      get 'generate_rank_csv'
    end
  end




  namespace :admin do
    resources :players do
      collection do
        post 'import'
      end
    end

    resources :tournaments do
      member { post 'add_to_rank' }
    end

    root :to => 'tournaments#index'
  end


  namespace :rank do

    resources :rank_places, path: 'player_results', as: 'player_results'

    match 'upload_results', to: 'rank_places#upload_results'
    match 'preview_tournament', to: 'rank_places#preview_tournament'

    root :to => 'rank_places#index'
  end

  root :to => 'tournaments#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user
  belongs_to :tournament

  default_scope :order => 'created_at DESC'
  friendly_id :name, use: [:slugged, :scoped], scope: :tournament

  after_create :notify_players

  def notify_players
    return true if !tournament.new?
    players = tournament.tournament_registrations.where('player_email is not NULL').where('player_email != ?', '')
    players.each do |p|
      RegistrationsMailer.notify_about_new_post(self, p).deliver
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :login_required, :only => [:new, :edit, :destroy]
  before_filter :load_tournament, :load_pages

  # GET /posts
  # GET /posts.json
  def index
    @posts = @tournament.posts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = @tournament.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @tournament.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to tournament_post_path(@tournament, @post), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to tournament_post_path(@tournament, @post), notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to tournament_posts_url(@post.tournament) }
      format.json { head :ok }
    end
  end

  private

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.clearfix
  = f.label :name, 'Tytuł', :class => :label
  .input
    = f.text_field :name, :class => 'text_field'
.clearfix
  = f.label :body, 'Treść', :class => :label
  .input
    = f.text_area :body, {:class => "tinymce text_area", :rows => 40, :cols => 160}
    = tinymce
.clearfix
  = f.label :user_id, t("activerecord.attributes.post.user_id", :default => "User"), :class => :label


.form-actions
  %button{:class => "btn primary", :type => "submit"} Save
  or
  = link_to "Cancel", tournament_posts_path(@tournament)

app/views/posts/_post.html.haml
.span8.center
  .post.center
    %h2
      = link_to post.name, tournament_post_path(@tournament, post), :style => "text-decoration:none"
    .body
      = redcloth(post.body)
    .date
      ="Dodano #{post.created_at} przez admin"
    -if logged_in? && (current_user == @tournament.user || current_user.admin?)
      .links
        = link_to "Show", tournament_post_path(@tournament, post)
        = link_to "Edit", edit_tournament_post_path(@tournament, post)
        = link_to "Destroy", tournament_post_path(@tournament, post), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"

app/views/posts/edit.html.haml
= form_for @post, :url => tournament_post_path(@tournament, @post), :html => { :class => "edit_post", :id => "edit_post" } do |f|
  %input{:name => "_method", :type => "hidden", :value =>"put"}
  = render :partial => "form", :locals => {:f => f}

app/views/posts/index.html.haml
-if @posts.any?
  -@posts.each do |post|
    =render :partial => 'post', :locals => {:post => post}
-else
  %h3
    Nie ma jeszcze żandych wpisów
.span8.center
  -if logged_in? && (current_user == @tournament.user || current_user.admin?)
    = link_to "Dodaj post", new_tournament_post_path(@tournament), :class => 'btn'

app/views/posts/new.html.haml
= form_for @post, :url => tournament_posts_path, :html => { :class => :form } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/posts/show.html.haml
%label{:class => "label"}= t("activerecord.attributes.post.name", :default => t("activerecord.labels.name", :default => "Name")) + ":"
%p= @post.name
%label{:class => "label"}= t("activerecord.attributes.post.body", :default => t("activerecord.labels.body", :default => "Body")) + ":"
%p= redcloth(@post.body)

.form-actions
  = link_to "Back", tournament_posts_path(@tournament), :class => 'btn'
  = link_to "Edit", edit_tournament_post_path(@tournament, @post), :class => 'btn'
  = link_to "Delete", tournament_post_path(@tournament, @post), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'