config/routes.rb
Dmp40k::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match '/rules' => 'pages#rules', :as => 'rules'

  match '/painting_contest' => 'pages#contest', :as => 'contest'

  match '/directions' => 'pages#directions', :as => 'directions'

  match '/admin' => 'admin#index'

  resources :players do
    resources :tournament_registrations
  end

  resources :sessions

  resources :users

  resources :teams

  resources :hostel_bookings do
    member do
      get 'toggle_payment'
    end
  end


  resources :tournaments do
    namespace :play do
      resources :players
      resources :results
      resources :tournaments
      resources :tournament_pairings, :as => 'pairings', :only => [:index, :update, :show]
    end
    resource :play
    resources :posts
    resources :pages do
      member { post :mercury_update }
    end

    resources :team_registrations do
      member do
        get 'toggle'
      end
    end

    resources :tournament_registrations, :path => "registrations" do
      collection do
        get 'players'
      end
      member do
        get 'toggle_payment', :as => 'toggle_payment'
        get 'toggle_rosters'
        get 'toggle_rosters_validation'
      end
    end
    member do
      get 'generate_pairings'
      get 'results'
      get 'current_round'
      get 'generate_rank_csv'
    end
  end




  namespace :admin do
    resources :players do
      collection do
        post 'import'
      end
    end

    resources :tournaments do
      member { post 'add_to_rank' }
    end

    root :to => 'tournaments#index'
  end


  namespace :rank do

    resources :rank_places, path: 'player_results', as: 'player_results'

    match 'upload_results', to: 'rank_places#upload_results'
    match 'preview_tournament', to: 'rank_places#preview_tournament'

    root :to => 'rank_places#index'
  end

  root :to => 'tournaments#index'
end

app/models/tournament_registration.rb
#encoding: utf-8
class TournamentRegistration < ActiveRecord::Base

  MONITORED_ATTRS = ['roster_send', 'roster_valid', 'payment_send']

  acts_as_paranoid 
  validates_as_paranoid

  belongs_to :tournament
  belongs_to :player
  has_many :pairings, :class_name => 'TournamentPairing', :finder_sql => Proc.new {
    %Q{
      SELECT DISTINCT *
      FROM tournament_pairings AS tp
      WHERE tp.player1_id = #{player.id} OR tp.player2_id = #{player.id}
    }
  }

  validates_uniqueness_of_without_deleted :player_id, :scope => :tournament_id
  validates_presence_of :player_id
  validates_uniqueness_of_without_deleted :player_email, :scope => :tournament_id, :allow_blank => true

  after_create :notify_player, :unless => Proc.new{ self.player_email.blank? }
  after_update :notify_player_of_change, :unless => Proc.new{ self.player_email.blank? }


  def notify_player
    RegistrationsMailer.tournament_signup_confirmation(self).deliver
  end

  def notify_player_of_change
    if change = (self.changed & MONITORED_ATTRS).first
      if self.send(change)
        RegistrationsMailer.tournament_change_confirmation(self, change).deliver    
      end
    end
  end


  def  self.to_csv(results)
    CSV.generate(:col_sep => ';') do |csv|
      csv << ['Miejsce', 'ID Ligowe', 'Imię', 'Nazwisko', 'Armia Miasto', 'Punkty', 'ID Sedziowka']
      results.each_with_index do |registration, i|
        csv << [
                i + 1,
                registration.player.league_id,
                registration.player.first_name,
                registration.player.last_name,
                registration.army,
                registration.player.city,
                registration.player.nick,
               ] 
      end 
    end 
  end

  def victory_points
    player.game_points_for_tournament(tournament)
  end
  
  def final_points
    current_points + extra_points - penalty_points
  end

end

app/controllers/tournament_registrations_controller.rb
#encoding: utf-8
class TournamentRegistrationsController < ApplicationController

  before_filter :load_tournament, :load_pages

  def index
    @player = Player.new
    if @tournament.for_teams?
      @registrations = @tournament.team_registrations.order('paid_at is NULL, paid_at ASC, created_at ASC')
      @team_registration = @tournament.team_registrations.new
      @tournament.team_members_count.times { @team_registration.team_registration_players.build }
    else
      @registrations = @tournament.tournament_registrations.includes([:player]).order('paid_at is NULL, paid_at ASC, created_at ASC')
      @tournament_registration = @tournament.tournament_registrations.new
      @players = Player.find(:all, :order => ('last_name ASC'))
    end 
  end

  def create
    registration = TournamentRegistration.new(params[:tournament_registration])
    if registration.save
      redirect_to :back, :notice => "Dodano zgłoszenie"
    else
      redirect_to :back, :alert => "Nie udało się dodać zgłoszenia"
    end
  end

  def edit
    if @tournament.for_teams?
      @team_registration = @tournament.team_registrations.find(params[:id])
    else
      @tournament_registration = @tournament.tournament_registrations.find(params[:id])
    end
  end
  
  def update
    @registration = TournamentRegistration.find(params[:id])
    if @registration.update_attributes(params[:tournament_registration])
      redirect_to tournament_tournament_registrations_path(@tournament), :notice => "Zgłoszenie uaktualnione"
    else
      render :edit, :alert => "Nie udało się uaktualnić zgłoszenia"
    end
  end

  def destroy
    registration = TournamentRegistration.find(params[:id])
    if registration.destroy
      redirect_to tournament_tournament_registrations_path(@tournament), :notice => "Usunięto zgłoszenie"
    else
      redirect_to :back, :notice => "Nie udało się usunąć zgłoszenia"
    end
  end
  

  def toggle_payment
    reg = TournamentRegistration.find(params[:id])
    if reg.payment_send 
      reg.payment_send = false 
      reg.paid_at = nil
    else
      reg.payment_send = true
      reg.paid_at = Time.now
    end
    reg.save
    redirect_to :back
  end

  def toggle_rosters
    reg = TournamentRegistration.find(params[:id])
    reg.roster_send? ? reg.roster_send = false : reg.roster_send = true
    reg.save
    redirect_to :back
  end

  def toggle_rosters_validation
    reg = TournamentRegistration.find(params[:id])
    reg.roster_valid? ? reg.roster_valid = false : reg.roster_valid = true
    reg.save
    redirect_to :back
  end
end

app/views/tournament_registrations/_form.html.haml
-if @tournament_registration.new_record? 
  - url = tournament_tournament_registrations_path
-else
  - url = tournament_tournament_registration_path(@tournament, @tournament_registration)

.add_team.span3
  %p
    Dodaj zgłoszenie
  = form_for @tournament_registration, :url => url do |f|
    %p
      = f.label :player_id, "Wybierz gracza"
      = f.hidden_field :player_id, class: 'player-id_0'
      = text_field_tag :player, params[:player_id] || nil , class: 'typeahead', data: { index: 0 }
    %p
      = f.label :army, "Armia"
      = f.select :army, options_for_select(Player::Armies), :include_blank => true
      = f.hidden_field :tournament_id, :value => @tournament.id
    %p
      =f.label :player_email, "Email gracza"
      = f.email_field :player_email
    -if @tournament_registration.new_record?
      %button{:type => 'submit'}
        Wyślij zgłoszenie
    -else
      %p
        = f.label :payment_send, "Przedpłata"
        = f.check_box :payment_send
      %p
        = f.label :roster_send, "Rozpiska"
        = f.check_box :roster_send
      %p
        = f.label :roster_valid, "Rozpiska poprawne?"
        = f.check_box :roster_valid
      %p
        %button{:type => 'submit'}
          Uaktualnij zgłoszenie
  %p

    
    
= render partial: 'player_form' if @tournament_registration.new_record?
 

app/views/tournament_registrations/_player_form.html.haml
.add_player
  %p
    Dodaj nowego gracza
  = form_for @player do |f|
    %p
      = f.label :league_id, "ID ligowe"
      = f.text_field :league_id
    %p
      = f.label :first_name, "Imię"
      = f.text_field :first_name
    %p
      = f.label :last_name, "Nazwisko"
      = f.text_field :last_name
    %p
      = f.label :nick, "Nick"
      = f.text_field :nick
    %p
      = f.label :city, "Miasto"
      = f.text_field :city
    %p
      %label
        Armia
      = select_tag :army, options_for_select(Player::Armies), :include_blank => true 
      = hidden_field_tag :tournament_id, @tournament.id
        
    %p  
      %button{:type => 'submit'}
        Dodaj gracza
    

app/views/tournament_registrations/_registration.html.haml
%tr
  %th
    = "#{i + 1}"
  %th
    =reg.player.full_name
  %th
    =reg.player.city
  %th
    =reg.army
  %th
    =reg.payment_send? ? "tak" : "nie"
    -if owner_or_admin?
      =link_to "", toggle_payment_tournament_tournament_registration_path(@tournament, reg), :style => "margin-left:8px", :class => "#{reg.payment_send? ? 'icon-remove' : 'icon-ok'}"
  %th
    =reg.roster_send? ? "tak" : "nie"
    -if owner_or_admin?
      =link_to "", toggle_rosters_tournament_tournament_registration_path(@tournament, reg), :style => "margin-left:8px", :class => "#{reg.roster_send? ? 'icon-remove' : 'icon-ok'}"
  %th
    =reg.roster_valid? ? "tak" : "nie"
    -if owner_or_admin?
      =link_to "", toggle_rosters_validation_tournament_tournament_registration_path(@tournament, reg), :style => "margin-left:8px", :class => "#{reg.roster_valid? ? 'icon-remove' : 'icon-ok'}"
  -if owner_or_admin?
    %th
      =link_to "", edit_tournament_tournament_registration_path(@tournament, reg), :class => 'icon-edit', :title => 'Edytuj'
      
      =link_to "", tournament_tournament_registration_path(@tournament, reg), :class => 'icon-remove', :method => :delete, :confirm => "Are you sure?", :title => 'Usuń zgłoszenie'

app/views/tournament_registrations/_team_edit_form.html.haml
-if @team_registration.new_record? 
  - url = tournament_team_registrations_path
-else
  - url = tournament_team_registration_path(@tournament, @team_registration)

.add_team.span3
  %p
    Dodaj zgłoszenie
  = form_for @team_registration, :url => url do |f|
    %p
      = f.label :name, 'Nazwa drużyny'
      = f.text_field :name
    %p
      = f.label :city, 'Miasto'
      = f.text_field :city
    %p
      -@team_registration.team_registration_players.each_with_index do |player, index|
        = f.fields_for :team_registration_players, player do |p|
          = p.label "Gracz nr #{ index + 1 }"
          = p.hidden_field :player_id, class: "player-id_#{index}"
          = text_field_tag :player, player.player.full_name_with_id || nil , class: 'typeahead', data: { index: index }
          = p.label :army, "Armia"
          = p.select :army, options_for_select(Player::Armies, selected: player.army), :include_blank => true
    -if @team_registration.new_record?
      %button{:type => 'submit'}
        Wyślij zgłoszenie
    -else
      %p
        = f.label :payment_send, "Przedpłata"
        = f.check_box :payment_send
      %p
        = f.label :roster_send, "Rozpiska"
        = f.check_box :roster_send
      %p
        = f.label :roster_valid, "Rozpiska poprawne?"
        = f.check_box :roster_valid
      %p
        %button{:type => 'submit'}
          Uaktualnij zgłoszenie

app/views/tournament_registrations/_team_form.html.haml
-if @team_registration.new_record? 
  - url = tournament_team_registrations_path
-else
  - url = tournament_team_registration_path(@tournament, @team_registration)

.add_team.span3
  %p
    Dodaj zgłoszenie
  = form_for @team_registration, :url => url do |f|
    %p
      = f.label :name, 'Nazwa drużyny'
      = f.text_field :name
    %p
      = f.label :city, 'Miasto'
      = f.text_field :city
    %p
      -@team_registration.team_registration_players.each_with_index do |player, index|
        = f.fields_for :team_registration_players, player do |p|
          = p.label "Gracz nr #{ index + 1 }"
          = p.hidden_field :player_id, class: "player-id_#{index}"
          = text_field_tag :player, params[:player_id] || nil , class: 'typeahead', data: { index: index }
          = p.label :army, "Armia"
          = p.select :army, options_for_select(Player::Armies), :include_blank => true
    -if @team_registration.new_record?
      %button{:type => 'submit'}
        Wyślij zgłoszenie
    -else
      %p
        = f.label :payment_send, "Przedpłata"
        = f.check_box :payment_send
      %p
        = f.label :roster_send, "Rozpiska"
        = f.check_box :roster_send
      %p
        = f.label :roster_valid, "Rozpiska poprawne?"
        = f.check_box :roster_valid
      %p
        %button{:type => 'submit'}
          Uaktualnij zgłoszenie

= render partial: 'player_form' if @team_registration.new_record?

app/views/tournament_registrations/_team_registration.html.haml
%tr
  %th
    = "#{i + 1}"
  %th
    =reg.name
    %a{ class: 'btn players-popover right', data: {content: players_for(reg), html: true, placement: 'top'}}
      Gracze
  %th
    =reg.city
  %th
    =reg.payment_send? ? "tak" : "nie"
    -if owner_or_admin?
      =link_to "", toggle_tournament_team_registration_path(@tournament, reg, action_type: 'payment_send'), :style => "margin-left:8px", :class => "#{reg.payment_send? ? 'icon-remove' : 'icon-ok'}"
  %th
    =reg.roster_send? ? "tak" : "nie"
    -if owner_or_admin?
      =link_to "", toggle_tournament_team_registration_path(@tournament, reg, action_type: 'roster_send'), :style => "margin-left:8px", :class => "#{reg.roster_send? ? 'icon-remove' : 'icon-ok'}"
  %th
    =reg.roster_valid? ? "tak" : "nie"
    -if owner_or_admin?
      =link_to "", toggle_tournament_team_registration_path(@tournament, reg, action_type: 'roster_valid'), :style => "margin-left:8px", :class => "#{reg.roster_valid? ? 'icon-remove' : 'icon-ok'}"
  -if owner_or_admin?
    %th
      =link_to "", edit_tournament_tournament_registration_path(@tournament, reg), :class => 'icon-edit', :title => 'Edytuj'
      
      =link_to "", tournament_team_registration_path(@tournament, reg), :class => 'icon-remove', :method => :delete, :confirm => "Are you sure?", :title => 'Usuń zgłoszenie'

app/views/tournament_registrations/edit.html.haml
.add_team
  -if @tournament.for_teams
    =render :partial => 'team_edit_form'
  -else
    =render :partial => 'form'

app/views/tournament_registrations/index.html.haml
%table.table.table-bordered.tablesorter
  %thead
    %tr
      %th
        Lp.
      %th
        =@tournament.for_teams? ? 'Drużyna' : 'Gracz'  
      %th
        Miasto
      - unless @tournament.for_teams?
        %th
          Armia
      %th
        Przedpłata
      %th
        Rozpiska
      %th
        Rozpiska poprawne?
      -if logged_in?
        %th 
          Akcja
  %tbody
    -@registrations.each_with_index do |reg, i|
      =render :partial => @tournament.for_teams? ? 'team_registration' : 'registration', :locals => {:reg => reg, :i => i}
-if owner_or_admin? #&& @tournament.new? 
  -if @tournament.for_teams
    =render :partial => 'team_form'
  -else
    =render :partial => 'form'
:javascript
  $(document).ready(function() 
    { 
      $(".tablesorter").tablesorter(); 
    } 
  ); 